### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by ChrisProgramming2018** [daltskin/CustomVision-TensorFlow-CSharp#1]
Hello :),

I found your great project, one the way of also loading a Python model for a University project 
Maybe you are so kind that you could send it to me 
Because at the moment I don't understand why you use the 'loss' 
in the CustomVision.cs line 50 

Thank you very much for your help in advance 

Best Regards 
Chris

**Comment by VolodymyrChechel** [comment]
Did you solve this problem?

**Comment by DiegoVil** [comment]
I have the same issue. As soon as I arrive to this line : runner.AddInput(graph["Placeholder"][0], tensor).Fetch(graph["loss"][0]); I have "Object reference not set to an instance of an object." exception.This happens when I use my own model with my own labels. Maybe I am missing something. And agree is great project.

{System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomVisionCLI.CustomVision.Main() in C:\Users\XXXX\YYYYY\CustomVision-TensorFlow-CSharp-master\CustomVision-TensorFlow-CSharp-master\CustomVision.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ObjectEx.InvokeMainMethod(Object o)
   at PowerArgs.Args.<>c__DisplayClass15_1.<InvokeMain>b__1()
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClass15_0.<InvokeMain>b__0(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args, Func`1 defaultEval)
   at PowerArgs.Args.InvokeMain(CommandLineArgumentsDefinition definition, String[] args)
   at PowerArgs.Args.InvokeMain[T](String[] args)
   at CustomVisionCLI.Program.Main(String[] args) in C:\Users\XXX\YYYY\CustomVision-TensorFlow-CSharp-master\CustomVision-TensorFlow-CSharp-master\Program.cs:line 8}

**Comment by DiegoVil** [comment]
Ok, I know the reason of this problem. YOu need to do the project in customvision.ai from the beginning. In my previous test I have changed one iteration to compact.

**Comment by daltskin** [comment]
Correct - this is for CustomVision.ai projects only.
